"""updated the color scheme

Revision ID: 5af58a26bf4d
Revises: 096a91541866
Create Date: 2026-01-26 20:49:06.843541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5af58a26bf4d'
down_revision: Union[str, Sequence[str], None] = '096a91541866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('html_content', sa.Text(), nullable=True))
    op.drop_column('site_settings', 'footer_copyright')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('footer_copyright', mysql.TEXT(collation='utf8mb4_unicode_ci'), server_default=sa.text("'Powered By IT Centre Glorious Church Copyright @ 2023'"), nullable=True))
    op.drop_column('pages', 'html_content')
    # ### end Alembic commands ###
