"""removed page table

Revision ID: 7ef80420a8d6
Revises: 44b4d23e7027
Create Date: 2026-01-31 00:46:17.558106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ef80420a8d6'
down_revision: Union[str, Sequence[str], None] = '44b4d23e7027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_index(op.f('page_name'), table_name='pages')
    op.drop_table('pages')
    op.create_index(op.f('ix_blog_page_id'), 'blog_page', ['id'], unique=False)
    op.create_index(op.f('ix_branches_page_id'), 'branches_page', ['id'], unique=False)
    op.create_index(op.f('ix_contact_page_id'), 'contact_page', ['id'], unique=False)
    op.create_index(op.f('ix_departments_page_id'), 'departments_page', ['id'], unique=False)
    op.create_index(op.f('ix_events_page_id'), 'events_page', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_page_id'), 'gallery_page', ['id'], unique=False)
    op.create_index(op.f('ix_home_page_id'), 'home_page', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_page_id'), table_name='home_page')
    op.drop_index(op.f('ix_gallery_page_id'), table_name='gallery_page')
    op.drop_index(op.f('ix_events_page_id'), table_name='events_page')
    op.drop_index(op.f('ix_departments_page_id'), table_name='departments_page')
    op.drop_index(op.f('ix_contact_page_id'), table_name='contact_page')
    op.drop_index(op.f('ix_branches_page_id'), table_name='branches_page')
    op.drop_index(op.f('ix_blog_page_id'), table_name='blog_page')
    op.create_table('pages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('page_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('page_header_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('page_header_subtitle', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('page_header_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('history', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('history_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mission', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('mission_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vision', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('vision_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('values', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('values_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('institutions', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('institutions_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content1', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('content1_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content1_label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('content2', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('content2_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content2_label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('content3', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('content3_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content3_label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('news_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('news_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('partner_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('partner_section_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('partner_section_button_text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('partner_section_button_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('partner_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('events_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('events_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('statistics_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('statistics_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('partners_faith_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('partners_faith_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('testimonials_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('testimonial1_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('testimonial1_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('testimonial1_author', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('testimonial1_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('testimonial2_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('testimonial2_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('testimonial2_author', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('testimonial2_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('latest_news_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('latest_news_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('newsletter_section_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('newsletter_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gallery_filter_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gallery_content_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contact_info_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contact_form_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contact_partner_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contact_partner_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('contact_partner_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('contact_partner_button_text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('contact_partner_button_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('blog_content_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('blog_sidebar_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('blog_recent_posts_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('blog_categories_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('blog_newsletter_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('branches_content_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('departments_content_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('events_content_section_visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_published', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('published_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('html_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('page_name'), 'pages', ['page_name'], unique=True)
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    # ### end Alembic commands ###
