"""initial migration

Revision ID: a1ecad7b11f7
Revises: 
Create Date: 2026-01-24 03:24:32.522303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ecad7b11f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('institutions', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_id'), 'about', ['id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_id'), 'gallery_images', ['id'], unique=False)
    op.create_table('navigation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_items_id'), 'navigation_items', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('page_header_title', sa.String(), nullable=True),
    sa.Column('page_header_subtitle', sa.String(), nullable=True),
    sa.Column('page_header_visible', sa.Integer(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('history_visible', sa.Integer(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('mission_visible', sa.Integer(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('vision_visible', sa.Integer(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('values_visible', sa.Integer(), nullable=True),
    sa.Column('institutions', sa.Text(), nullable=True),
    sa.Column('institutions_visible', sa.Integer(), nullable=True),
    sa.Column('content1', sa.Text(), nullable=True),
    sa.Column('content1_visible', sa.Integer(), nullable=True),
    sa.Column('content1_label', sa.String(), nullable=True),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('content2_visible', sa.Integer(), nullable=True),
    sa.Column('content2_label', sa.String(), nullable=True),
    sa.Column('content3', sa.Text(), nullable=True),
    sa.Column('content3_visible', sa.Integer(), nullable=True),
    sa.Column('content3_label', sa.String(), nullable=True),
    sa.Column('news_section_title', sa.String(), nullable=True),
    sa.Column('news_section_visible', sa.Integer(), nullable=True),
    sa.Column('partner_section_title', sa.String(), nullable=True),
    sa.Column('partner_section_content', sa.Text(), nullable=True),
    sa.Column('partner_section_button_text', sa.String(), nullable=True),
    sa.Column('partner_section_button_url', sa.String(), nullable=True),
    sa.Column('partner_section_visible', sa.Integer(), nullable=True),
    sa.Column('events_section_title', sa.String(), nullable=True),
    sa.Column('events_section_visible', sa.Integer(), nullable=True),
    sa.Column('statistics_section_title', sa.String(), nullable=True),
    sa.Column('statistics_section_visible', sa.Integer(), nullable=True),
    sa.Column('partners_faith_section_title', sa.String(), nullable=True),
    sa.Column('partners_faith_section_visible', sa.Integer(), nullable=True),
    sa.Column('testimonials_section_visible', sa.Integer(), nullable=True),
    sa.Column('testimonial1_title', sa.String(), nullable=True),
    sa.Column('testimonial1_content', sa.Text(), nullable=True),
    sa.Column('testimonial1_author', sa.String(), nullable=True),
    sa.Column('testimonial1_visible', sa.Integer(), nullable=True),
    sa.Column('testimonial2_title', sa.String(), nullable=True),
    sa.Column('testimonial2_content', sa.Text(), nullable=True),
    sa.Column('testimonial2_author', sa.String(), nullable=True),
    sa.Column('testimonial2_visible', sa.Integer(), nullable=True),
    sa.Column('latest_news_section_title', sa.String(), nullable=True),
    sa.Column('latest_news_section_visible', sa.Integer(), nullable=True),
    sa.Column('newsletter_section_title', sa.String(), nullable=True),
    sa.Column('newsletter_section_visible', sa.Integer(), nullable=True),
    sa.Column('gallery_filter_section_visible', sa.Integer(), nullable=True),
    sa.Column('gallery_content_section_visible', sa.Integer(), nullable=True),
    sa.Column('contact_info_section_visible', sa.Integer(), nullable=True),
    sa.Column('contact_form_section_visible', sa.Integer(), nullable=True),
    sa.Column('contact_partner_section_visible', sa.Integer(), nullable=True),
    sa.Column('contact_partner_title', sa.String(), nullable=True),
    sa.Column('contact_partner_content', sa.Text(), nullable=True),
    sa.Column('contact_partner_button_text', sa.String(), nullable=True),
    sa.Column('contact_partner_button_url', sa.String(), nullable=True),
    sa.Column('blog_content_section_visible', sa.Integer(), nullable=True),
    sa.Column('blog_sidebar_section_visible', sa.Integer(), nullable=True),
    sa.Column('blog_recent_posts_section_visible', sa.Integer(), nullable=True),
    sa.Column('blog_categories_section_visible', sa.Integer(), nullable=True),
    sa.Column('blog_newsletter_section_visible', sa.Integer(), nullable=True),
    sa.Column('branches_content_section_visible', sa.Integer(), nullable=True),
    sa.Column('departments_content_section_visible', sa.Integer(), nullable=True),
    sa.Column('events_content_section_visible', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('site_name_font_family', sa.String(), nullable=True),
    sa.Column('site_name_font_size', sa.String(), nullable=True),
    sa.Column('site_name_font_weight', sa.String(), nullable=True),
    sa.Column('site_name_color', sa.String(), nullable=True),
    sa.Column('tagline_font_family', sa.String(), nullable=True),
    sa.Column('tagline_font_size', sa.String(), nullable=True),
    sa.Column('tagline_font_weight', sa.String(), nullable=True),
    sa.Column('tagline_color', sa.String(), nullable=True),
    sa.Column('theme_primary', sa.String(), nullable=True),
    sa.Column('theme_secondary', sa.String(), nullable=True),
    sa.Column('theme_success', sa.String(), nullable=True),
    sa.Column('theme_danger', sa.String(), nullable=True),
    sa.Column('theme_warning', sa.String(), nullable=True),
    sa.Column('theme_info', sa.String(), nullable=True),
    sa.Column('theme_light', sa.String(), nullable=True),
    sa.Column('theme_dark', sa.String(), nullable=True),
    sa.Column('hero_title', sa.Text(), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_button1_text', sa.String(), nullable=True),
    sa.Column('hero_button1_url', sa.String(), nullable=True),
    sa.Column('hero_button1_visible', sa.Integer(), nullable=True),
    sa.Column('hero_button2_text', sa.String(), nullable=True),
    sa.Column('hero_button2_url', sa.String(), nullable=True),
    sa.Column('hero_button2_visible', sa.Integer(), nullable=True),
    sa.Column('hero_image_url', sa.String(), nullable=True),
    sa.Column('hero_image_visible', sa.Integer(), nullable=True),
    sa.Column('hero_background_image_url', sa.String(), nullable=True),
    sa.Column('hero_background_image_visible', sa.Integer(), nullable=True),
    sa.Column('admin_emails', sa.Text(), nullable=True),
    sa.Column('admin_panel_title', sa.String(), nullable=True),
    sa.Column('feature_dashboard', sa.Integer(), nullable=True),
    sa.Column('feature_blog', sa.Integer(), nullable=True),
    sa.Column('feature_branches', sa.Integer(), nullable=True),
    sa.Column('feature_departments', sa.Integer(), nullable=True),
    sa.Column('feature_events', sa.Integer(), nullable=True),
    sa.Column('feature_gallery', sa.Integer(), nullable=True),
    sa.Column('feature_contact', sa.Integer(), nullable=True),
    sa.Column('feature_pages', sa.Integer(), nullable=True),
    sa.Column('feature_about', sa.Integer(), nullable=True),
    sa.Column('feature_navigation', sa.Integer(), nullable=True),
    sa.Column('feature_users', sa.Integer(), nullable=True),
    sa.Column('feature_settings', sa.Integer(), nullable=True),
    sa.Column('social_facebook_url', sa.String(), nullable=True),
    sa.Column('social_twitter_url', sa.String(), nullable=True),
    sa.Column('social_instagram_url', sa.String(), nullable=True),
    sa.Column('social_youtube_url', sa.String(), nullable=True),
    sa.Column('social_linkedin_url', sa.String(), nullable=True),
    sa.Column('social_section_visible', sa.Integer(), nullable=True),
    sa.Column('quick_links_section_visible', sa.Integer(), nullable=True),
    sa.Column('quick_links_pages', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('contact_office_hours', sa.Text(), nullable=True),
    sa.Column('contact_section_visible', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_navigation_items_id'), table_name='navigation_items')
    op.drop_table('navigation_items')
    op.drop_index(op.f('ix_gallery_images_id'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_about_id'), table_name='about')
    op.drop_table('about')
    # ### end Alembic commands ###
